services:
    postgres:
      image: postgres:13
      environment:
        POSTGRES_USER: dbt
        POSTGRES_PASSWORD: password1234
        POSTGRES_DB: dbt
      volumes:
        - ./raw_data:/input_data
        - ./temp:/temp
        - ./warehouse_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "dbt", "-U", "dbt" ]
        interval: 5s
        retries: 5
      restart: always
      ports:
        - "5432:5432"
