config:
  send_anonymous_usage_stats: False

dbt_local_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: password1234
      dbname: dbt
      schema: warehouse
